### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gui#45]
Since the GK API for registering users is ready:
```$ curl -X POST -H "Content-Type: application/json" -d '{"username": "test4", "password":"test2", "firstName": "firstName", "lastName": "lastName", "email": "mail4@mail.com", "phone_number":654654654,"user_type":"customer"}' sp.int3.sonata-nfv.eu:5000/api/v2/users```
we need to have a user registration page in the GUI.

**Comment by jbonnet** [comment]
Hi, guys,
Any prediction on when we can have this?

Our 8th, May (Monday) milestone is really the 5th, May (Friday), and next week has only 4 working days...

**Comment by mzacharioudakis** [comment]
It is ready
