### ISSUE TITLE
User loggin

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gui#46]
Since we have the GK API for logging users in ready
`$curl -X POST -d '{"username":"test1","password":"test2"}' sp.int3.sonata-nfv.eu:32001/api/v2/sessions`
we need to change the current loggin (with CitHub accounts) to the SP's.

**Comment by jbonnet** [comment]
Hi, guys,
Any prediction on when we can have this?

Our 8th, May (Monday) milestone is really the 5th, May (Friday), and next week has only 4 working days...

**Comment by pkarkazis** [comment]
We will make our best to have it until Friday

**Comment by mzacharioudakis** [comment]
Sorry for the delay - It was integrated - (before the meeting in Paris) so I close this issue
