### ISSUE TITLE
Use URL instead variables.php file

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-gui#60]
@mzacharioudakis Can we extract the URL from the browser instead to use the variables.php file?

Hint: https://stackoverflow.com/questions/20655877/angular-1-get-current-url-parameters

This would be for MON_URL, GK_URL and VIMS_URL. What do you think?

**Comment by mzacharioudakis** [comment]
The variables are extracted form url/browser as it is defined by angular design. However, the variables.php is used to grab variables/URLs from VM - environmental variables..

**Comment by felipevicens** [comment]
@mzacharioudakis can we change it? I think is better to extract from URL cause is difficult to know the public IP address and set inside the container. Is hard to change it?

**Comment by mzacharioudakis** [comment]
@felipevicens I am not sure that I understood correctly. The variables.php grabs the URLs of MON_URL, GK_URL etc from the environmental variables that the VM has. I added you on my skype in order to discuss it there.
